In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
from sklearn.cluster import KMeans

In [3]:
Data = pd.read_csv("smogon.csv")
DataMoves = Data["moves"].copy()

In [4]:
TextToNumbers = TfidfVectorizer(ngram_range=(1,1))
MatrixTextoToNumbers = TextToNumbers.fit_transform(DataMoves)

In [5]:
MatrixTextoToNumbers.shape[1]

1923

In [11]:
Names = TextToNumbers.get_feature_names_out()
indice = 0
for i in TextToNumbers.vocabulary_:
    indice +=1
indice

1923

In [7]:
MatrixTextoNumbersDataFrame = pd.DataFrame(MatrixTextoToNumbers.toarray(),columns=Names)
Cluster = KMeans(n_clusters=18,random_state=42)
ClustersPokemon = Cluster.fit(MatrixTextoNumbersDataFrame)
MatrixTextoNumbersDataFrame["Clusters"] = ClustersPokemon.labels_
MatrixTextoNumbersDataFrame.insert(0,"NombrePokemon",Data["Pokemon"] )
MatrixTextoNumbersDataFrame.to_csv("PokemonDataSet.csv",index = False )

In [8]:
MatrixTextoNumbersDataFrame

,NombrePokemon,10,100,16,16th,1hp,20,220,2normal,30,...,wrapnormal,wrathground,wreckerrock,wring,yawnnormal,yet,younormal,zap,zen,Clusters
0,Abomasnow,0.000000,0.000000,0.025145,0.0,0.0,0.0,0.000000,0.0,0.007253,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,2
1,Abra,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.006195,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.013850,0
2,Absol,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.010980,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.012273,6
3,Accelgor,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.007396,...,0.0,0.000000,0.0,0.0,0.022483,0.000000,0.000000,0.0,0.000000,13
4,Aegislash,0.000000,0.037652,0.000000,0.0,0.0,0.0,0.037652,0.0,0.008626,...,0.0,0.000000,0.0,0.0,0.000000,0.027001,0.027001,0.0,0.000000,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,Zoroark,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.013636,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,4
752,Zorua,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.014487,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,4
753,Zubat,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.007212,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.016123,14
754,Zweilous,0.066825,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.008395,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.018768,5
755,Zygarde,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.009101,...,0.0,0.061318,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.020346,5